/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;
/**
 *
 * @author nanik
 */
public class AddPersonJPanel extends javax.swing.JPanel {
    
        private JPanel userProcessContainer;
    private PersonDirectory personDirectory;

    /**
     * Creates new form AddPersonJPanel
     */
    public AddPersonJPanel(JPanel userProcessContainer, PersonDirectory personDirectory) {
        initComponents();
                this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtfirstname = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblTelephone = new javax.swing.JLabel();
        txtAddressLine1Home = new javax.swing.JTextField();
        txtAddressLine2Home = new javax.swing.JTextField();
        txtCityHome = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txtnationality = new javax.swing.JTextField();
        lblAddressLine1Home = new javax.swing.JLabel();
        lblAddressLine2Home = new javax.swing.JLabel();
        lblCityHome = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        lblStateHome = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        lblZipHome = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        lblNationality = new javax.swing.JLabel();
        txtStateHome = new javax.swing.JTextField();
        txtzip = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLasteName = new javax.swing.JLabel();
        lblTtileHome = new javax.swing.JLabel();
        lblTitleOffice = new javax.swing.JLabel();
        lblZipOffice = new javax.swing.JLabel();
        txtAddressLine1Office = new javax.swing.JTextField();
        txtAddressLine2Office = new javax.swing.JTextField();
        txtCityOffice = new javax.swing.JTextField();
        txtStateOffice = new javax.swing.JTextField();
        txtZipOffice = new javax.swing.JTextField();
        lblAddressLine1Office = new javax.swing.JLabel();
        lblAddressLine2Office = new javax.swing.JLabel();
        lblCityOffice = new javax.swing.JLabel();
        lblStateOffice = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lblEmail.setText("E-mail");

        lblTelephone.setText("Telephone");

        lblSsn.setText("SSN");

        lblAddressLine1Home.setText("Address line 1");

        lblAddressLine2Home.setText("Address line 2");

        lblCityHome.setText("City");

        lblStateHome.setText("State");

        lblZipHome.setText("Zip");

        txtssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtssnActionPerformed(evt);
            }
        });

        lblNationality.setText("Nationality");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbltitle.setText("Personal Profile");

        lblFirstName.setText("First Name");

        lblLasteName.setText("Last Name");

        lblTtileHome.setText("Home Address");

        lblTitleOffice.setText("Office Address");

        lblZipOffice.setText("Zip");

        lblAddressLine1Office.setText("Address line 1");

        lblAddressLine2Office.setText("Address line 2");

        lblCityOffice.setText("City");

        lblStateOffice.setText("State");

        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(83, 83, 83)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblTelephone)
                                    .addComponent(lblAddressLine1Home)
                                    .addComponent(lblAddressLine2Home)
                                    .addComponent(lblCityHome)
                                    .addComponent(lblSsn))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtCityHome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblStateHome)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtStateHome, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblZipHome)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(txtAddressLine2Home)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtssn)
                                            .addComponent(txtfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtphone))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(lblLasteName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblEmail)
                                                    .addComponent(lblNationality))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                    .addComponent(txtnationality)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(177, 177, 177))
                                    .addComponent(txtAddressLine1Home)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddressLine1Office)
                                    .addComponent(lblAddressLine2Office)
                                    .addComponent(lblCityOffice))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtCityOffice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblStateOffice)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtStateOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblZipOffice)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtZipOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE))
                                            .addComponent(txtAddressLine2Office))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtAddressLine1Office))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTtileHome)
                                .addGap(275, 275, 275))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTitleOffice)
                                .addGap(271, 271, 271))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName)
                    .addComponent(lblLasteName))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelephone)
                    .addComponent(lblNationality)
                    .addComponent(txtnationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(lblTtileHome)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine1Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressLine1Home))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine2Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressLine2Home))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStateHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityHome)
                    .addComponent(lblStateHome)
                    .addComponent(lblZipHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblTitleOffice)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine1Office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressLine1Office))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine2Office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressLine2Office))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStateOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZipOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityOffice)
                    .addComponent(lblStateOffice)
                    .addComponent(lblZipOffice))
                .addGap(46, 46, 46)
                .addComponent(btnSave)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtssnActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtfirstname.getText().isEmpty() || txtlastname.getText().isEmpty() ||
            txtssn.getText().isEmpty() || txtnationality.getText().isEmpty() ||
            txtphone.getText().isEmpty() || txtemail.getText().isEmpty() ||
            txtAddressLine1Home.getText().isEmpty() || txtCityHome.getText().isEmpty() ||
            txtStateHome.getText().isEmpty() || txtzip.getText().isEmpty() ||
            txtAddressLine1Office.getText().isEmpty() || txtCityOffice.getText().isEmpty() ||
            txtStateOffice.getText().isEmpty() || txtZipOffice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create home and office address objects
        String firstName = txtfirstname.getText();
        String lastName = txtlastname.getText();
        String ssn = txtssn.getText();
        String nationality = txtnationality.getText(); // Nationality is typically a String
        String email = txtemail.getText();
        String phoneNumber = txtphone.getText();

// Collecting Address information for home and office
         Address homeAddress = new Address(txtAddressLine1Home.getText(), txtAddressLine2Home.getText(),
                                  txtCityHome.getText(), txtStateHome.getText(), txtzip.getText(), txtphone.getText());

         Address officeAddress = new Address(txtAddressLine1Office.getText(), txtAddressLine2Office.getText(),
                                    txtCityOffice.getText(), txtStateOffice.getText(), txtZipOffice.getText(), txtphone.getText());

// Creating the Person object with the correct constructor
         Person person = new Person(firstName, lastName, ssn, nationality, email, phoneNumber, homeAddress, officeAddress);
        // Add the person to the directory
        personDirectory.addPerson(person);

        // Notify user and reset fields
        JOptionPane.showMessageDialog(null, "Person added successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
        resetFields();


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    userProcessContainer.removeAll();
    userProcessContainer.repaint();
    userProcessContainer.revalidate();
    }//GEN-LAST:event_btnBackActionPerformed

private void resetFields() {
        txtfirstname.setText("");
        txtlastname.setText("");
        txtssn.setText("");
        txtnationality.setText("");
        txtphone.setText("");
        txtemail.setText("");
        txtAddressLine1Home.setText("");
        txtAddressLine2Home.setText("");
        txtCityHome.setText("");
        txtStateHome.setText("");
        txtzip.setText("");
        txtAddressLine1Office.setText("");
        txtAddressLine2Office.setText("");
        txtCityOffice.setText("");
        txtStateOffice.setText("");
        txtZipOffice.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddressLine1Home;
    private javax.swing.JLabel lblAddressLine1Office;
    private javax.swing.JLabel lblAddressLine2Home;
    private javax.swing.JLabel lblAddressLine2Office;
    private javax.swing.JLabel lblCityHome;
    private javax.swing.JLabel lblCityOffice;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLasteName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblStateHome;
    private javax.swing.JLabel lblStateOffice;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblTitleOffice;
    private javax.swing.JLabel lblTtileHome;
    private javax.swing.JLabel lblZipHome;
    private javax.swing.JLabel lblZipOffice;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField txtAddressLine1Home;
    private javax.swing.JTextField txtAddressLine1Office;
    private javax.swing.JTextField txtAddressLine2Home;
    private javax.swing.JTextField txtAddressLine2Office;
    private javax.swing.JTextField txtCityHome;
    private javax.swing.JTextField txtCityOffice;
    private javax.swing.JTextField txtStateHome;
    private javax.swing.JTextField txtStateOffice;
    private javax.swing.JTextField txtZipOffice;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables
}
